file -inlinebatch END_OF_BATCH

DROP FUNCTION GREATEST IF EXISTS;
DROP FUNCTION LEAST IF EXISTS;
DROP FUNCTION SIGN2 IF EXISTS;
DROP FUNCTION arbitraryTruncateWithBaseTime IF EXISTS;
DROP FUNCTION arbitraryTruncate             IF EXISTS;

END_OF_BATCH